In [38]:
import pandas as pd
from datetime import datetime
import math

In [3]:
df = pd.read_csv("ventas2.tsv", sep='\t')

In [4]:
df.head()

,Almacen,Fecha,Factura,Cliente,Total venta,Margen de utilidad,Comensales
0,Mi llanerita,2024-09-28 10:48:47,FVE818,Consumidor final,15500,11619,1
1,Mi llanerita,2024-09-28 10:48:10,FVE817,Consumidor final,35600,32963,1
2,Mi llanerita,2024-09-28 10:47:44,FVE816,Consumidor final,37500,34722,1
3,Mi llanerita,2024-09-28 10:47:37,FVE815,Consumidor final,31600,29260,1
4,Mi llanerita,2024-09-28 10:15:29,FVE814,Consumidor final,50700,46945,1

In [5]:
fv_df = df[df['Factura'].str.startswith('FVE')]

In [10]:
fv_df["Factura"] = fv_df["Factura"].apply(lambda data: data.replace("FVE", ""))

/var/folders/2w/1szd455139q6yvlfqp61wgh8bh77xm/T/ipykernel_61677/473658236.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fv_df["Factura"] = fv_df["Factura"].apply(lambda data: data.replace("FVE", ""))

In [13]:
fv_df.dtypes

Almacen               object
Fecha                 object
Factura               object
Cliente               object
Total venta           object
Margen de utilidad    object
Comensales             int64
dtype: object

In [18]:
def to_date(data: str) -> str:
    data = data.split(" ")[0]
    time = datetime.strptime(data, '%Y-%m-%d')
    year = time.year
    month = time.month
    day = time.day
    return f"{day}/{month}/{year}"

In [19]:
fv_df["Fecha"] = fv_df["Fecha"].apply(to_date)

/var/folders/2w/1szd455139q6yvlfqp61wgh8bh77xm/T/ipykernel_61677/2184831535.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fv_df["Fecha"] = fv_df["Fecha"].apply(to_date)

In [40]:
fv_df["valor_unidatio"] = fv_df["Total venta"].apply(lambda valor: round(float(valor.split(",")[0])/1.08, 4))

/var/folders/2w/1szd455139q6yvlfqp61wgh8bh77xm/T/ipykernel_61677/865162140.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fv_df["valor_unidatio"] = fv_df["Total venta"].apply(lambda valor: round(float(valor.split(",")[0])/1.08, 4))

In [41]:
fv_df.head()

,Almacen,Fecha,Factura,Cliente,Total venta,Margen de utilidad,Comensales,valor_unidatio
0,Mi llanerita,28/9/2024,818,Consumidor final,15500,11619,1,14351.8519
1,Mi llanerita,28/9/2024,817,Consumidor final,35600,32963,1,32962.9630
2,Mi llanerita,28/9/2024,816,Consumidor final,37500,34722,1,34722.2222
3,Mi llanerita,28/9/2024,815,Consumidor final,31600,29260,1,29259.2593
4,Mi llanerita,28/9/2024,814,Consumidor final,50700,46945,1,46944.4444

In [42]:
fv_df.to_csv("cleaned.tsv", sep="\t")

In [43]:
mitad = int(fv_df.shape[0]/2)

In [44]:
df1 = fv_df.iloc[:mitad]
df2 = fv_df.iloc[mitad:]

In [47]:
df1.to_csv("cleaned1.tsv", sep="\t")

In [48]:
df2.to_csv("cleaned2.tsv", sep="\t")

In [49]:
mitad

404